### ISSUE TITLE
Desired values for blameable field get overwritten

### ISSUE THREAD

**Issue by arnordhaenens** [astalpaert/laravel-blamable#9]
Currently, the package does not take into account custom set values for any of the blameable fields. 

Example: When creating an entity, and setting the `created_by` value to a specific value, that value will not be persisted as desired. 
This happens for all blameable fields and for each state (creating, updating, deleting). 

The package should persist any manually set values.

**Comment by astalpaert** [comment]
@arnordhaenens Should be fixed in latest version, see #13 :-)
